### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by wjn161** [fshows-com/deep-in-java#1]
#### 格式

- 姓名：
- 作业地址：

**Comment by wjn161** [comment]
#### 示例：

姓名：吴建南
作业地址：http://www.google.com

**Comment by kiwiflydream** [comment]
姓名：卜浩
作业地址：[week-01](https://github.com/kiwiflydream/deep-in-java/tree/main/week-01)

**Comment by fschenlx** [comment]
姓名：陈龙祥
作业地址：https://github.com/fschenlx/deep-in-java/tree/main/week-01

**Comment by bigwheat** [comment]
姓名：杨俊
作业地址：[week-01](https://github.com/bigwheat/deep-in-java/tree/main/week-01)

**Comment by PopaiZhou** [comment]
姓名：周江沛
作业地址：[week-01](https://github.com/PopaiZhou/deep-in-java/tree/main/week-01)

**Comment by yangder** [comment]
姓名：杨德伟
作业地址：[week-01](https://github.com/yangder/deep-in-java/tree/main/week-01)

**Comment by zhangxj316** [comment]
姓名：张晓杰
作业地址：[week-01](https://github.com/zhangxj316/deep-in-java/tree/main/week-01)

**Comment by linzhenyu** [comment]
姓名：林振宇
作业地址：[week-01](https://github.com/linzhenyu/deep-in-java/tree/main/week-01)

**Comment by xiaozhu521** [comment]
姓名：朱天荣
作业地址：[deep-in-jvm](https://github.com/xiaozhu521/deep-in-java/tree/main/deep-in-jvm)

**Comment by zngit-pro** [comment]
姓名：张宁
作业地址：[week-01](https://github.com/zngit-pro/deep-in-java/tree/main/week-01)

**Comment by liluqing** [comment]
姓名: 李露清
作业地址：https://github.com/liluqing/deep-in-java/tree/main/week-01

**Comment by you1244792128** [comment]
姓名：尤明明
作业地址：https://github.com/you1244792128/deep-in-java/tree/main/week-01

**Comment by wangjianguan** [comment]
姓名：王建观
作业地址：[week-01](https://github.com/wangjianguan/deep-in-java/tree/main/week-01)

**Comment by Maweiming** [comment]
姓名：马伟明
作业地址：[week01](https://github.com/Maweiming/deep-in-java/tree/main/week-01)
