### ISSUE TITLE
第二周作业

### ISSUE THREAD

**Issue by wjn161** [fshows-com/deep-in-java#3]

**Comment by Maweiming** [comment]
姓名：马伟明
作业地址：[week-02](https://github.com/Maweiming/deep-in-java/tree/main/week-02)

**Comment by linzhenyu** [comment]
姓名：林振宇
作业地址：[week-02](https://github.com/linzhenyu/deep-in-java/tree/main/week-02)

**Comment by wangjianguan** [comment]
姓名：王建观
作业地址：[week-03](https://github.com/wangjianguan/deep-in-java/tree/main/week-02)

**Comment by bigwheat** [comment]
姓名：杨俊
作业地址：[week-02](https://github.com/bigwheat/deep-in-java/tree/main/week-02)

**Comment by zhangxj316** [comment]
姓名：张晓杰
作业地址：[week-02](https://github.com/zhangxj316/deep-in-java/tree/main/week-02)

**Comment by kiwiflydream** [comment]
姓名：卜浩
作业地址：[week-02](https://github.com/kiwiflydream/deep-in-java/tree/main/src/main/java/com/fshows/deepinjava/week02)

**Comment by liluqing** [comment]
姓名：李露清
作业地址：[week-02](https://github.com/liluqing/deep-in-java/tree/main/week-02)

**Comment by zngit-pro** [comment]
姓名：张宁
作业地址：[week-02](https://github.com/zngit-pro/deep-in-java/tree/main/week-02)

**Comment by yangder** [comment]
姓名：杨德伟
作业地址：[week-02](https://github.com/yangder/deep-in-java/tree/main/week-02)
